/* FocusForge - Security Improved */
function escapeHtml(str){if(str===null||str===undefined)return'';const div=document.createElement('div');div.textContent=String(str);return div.innerHTML;}
async function hashPassword(password){const encoder=new TextEncoder();const data=encoder.encode(password);const hashBuffer=await crypto.subtle.digest('SHA-256',data);const hashArray=Array.from(new Uint8Array(hashBuffer));return hashArray.map(b=>b.toString(16).padStart(2,'0')).join('');}
async function verifyPassword(password,storedHash){const hash=await hashPassword(password);return hash===storedHash;}
function stateKey(){const user=getCurrentUser();return user?'focusforge-state-'+user.email:'focusforge-state';}
function getCurrentUser(){const stored=localStorage.getItem('focusforge-user');return stored?JSON.parse(stored):null;}
function getAllUsers(){const stored=localStorage.getItem('focusforge-all-users');if(stored){try{return JSON.parse(stored);}catch(e){return[];}}return[];}
function saveAllUsers(users){localStorage.setItem('focusforge-all-users',JSON.stringify(users));}
const defaultSubjects={mathematics:{name:'Mathematics',color:'#a855f7',icon:'📐',chapters:[{id:'math-1',name:'Quadratic Equations',priority:'high',completed:false,rating:0,xp:0},{id:'math-2',name:'Arithmetic Progressions',priority:'high',completed:false,rating:0,xp:0},{id:'math-3',name:'Trigonometry',priority:'high',completed:false,rating:0,xp:0}]},physics:{name:'Physics',color:'#22d3ee',icon:'🔬',chapters:[{id:'phy-1',name:'Electrostatics',priority:'high',completed:false,rating:0,xp:0},{id:'phy-2',name:'Current Electricity',priority:'high',completed:false,rating:0,xp:0}]},chemistry:{name:'Chemistry',color:'#10b981',icon:'🧪',chapters:[{id:'chem-1',name:'Periodic Table',priority:'high',completed:false,rating:0,xp:0},{id:'chem-2',name:'Chemical Bonding',priority:'high',completed:false,rating:0,xp:0}]},english:{name:'English',color:'#6366f1',icon:'📖',chapters:[{id:'eng-1',name:'Grammar - Tenses',priority:'high',completed:false,rating:0,xp:0},{id:'eng-2',name:'Active & Passive Voice',priority:'high',completed:false,rating:0,xp:0}]},biology:{name:'Biology',color:'#22c55e',icon:'🌿',chapters:[{id:'bio-1',name:'Cell Division & Genetics',priority:'high',completed:false,rating:0,xp:0},{id:'bio-2',name:'Photosynthesis',priority:'high',completed:false,rating:0,xp:0}]}};
const achievementsData=[{id:'first-session',name:'First Blood',icon:'🎯'},{id:'streak-3',name:'On Fire',icon:'🔥'},{id:'streak-7',name:'Week Warrior',icon:'💪'},{id:'sessions-10',name:'Marathon',icon:'🏃'},{id:'hours-10',name:'Time Keeper',icon:'⏰'},{id:'perfect-day',name:'Perfect Day',icon:'⭐'}];
const levelsData=[{level:1,name:'CADET',xpRequired:0},{level:2,name:'ENSIGN',xpRequired:100},{level:3,name:'LIEUTENANT',xpRequired:300},{level:4,name:'CAPTAIN',xpRequired:600},{level:5,name:'MAJOR',xpRequired:1000}];
const colors=['#6366f1','#ec4899','#22d3ee','#10b981','#f59e0b','#a855f7','#ef4444','#06b6d4'];
let state={user:{name:'Student',level:1,xp:0,streak:{count:0,lastDate:null}},subjects:{},sessions:[],achievements:{},stats:{totalStudyTime:0,sessionsCompleted:0,longestStreak:0}};
let currentUser=null,selectedColor='#6366f1',selectedIcon='📚',selectedPriority='high',newUserRole='student',editUserRole='student',testMarks=50,selectedDuration=25,sessionType='focus';
let timerInterval=null,timerSeconds=25*60,timerRunning=false,timerPaused=false,sessionStartTime=null,currentSubjectId=null;
function init(){createParticles();loadState();showLogin();setupEventListeners();}
function createParticles(){const container=document.getElementById('bgAnimation');if(!container)return;container.innerHTML='';for(let i=0;i<30;i++){const particle=document.createElement('div');particle.className='particle';particle.style.left=Math.random()*100+'%';particle.style.animationDuration=(15+Math.random()*15)+'s';particle.style.animationDelay=Math.random()*20+'s';particle.style.background=colors[Math.floor(Math.random()*colors.length)];container.appendChild(particle);}}
function setupEventListeners(){document.querySelectorAll('#colorPicker .color-option').forEach(opt=>{opt.addEventListener('click',()=>selectColor(opt));});document.querySelectorAll('#iconPicker .icon-option').forEach(opt=>{opt.addEventListener('click',()=>selectIcon(opt));});document.querySelectorAll('.modal-overlay').forEach(overlay=>{overlay.addEventListener('click',(e)=>{if(e.target===overlay)overlay.classList.remove('active');});});document.addEventListener('keydown',(e)=>{if(e.key==='Escape'){document.querySelectorAll('.modal-overlay.active').forEach(modal=>{modal.classList.remove('active');});}});}
function loadState(){const saved=localStorage.getItem(stateKey());if(saved){try{state=JSON.parse(saved);}catch(e){resetStateToDefault();}}else{resetStateToDefault();}if(Object.keys(state.achievements).length===0){achievementsData.forEach(a=>{state.achievements[a.id]=false;});}checkStreak();saveState();}
function resetStateToDefault(){state={user:{name:'Student',level:1,xp:0,streak:{count:0,lastDate:null}},subjects:JSON.parse(JSON.stringify(defaultSubjects)),sessions:[],achievements:{},stats:{totalStudyTime:0,sessionsCompleted:0,longestStreak:0}};achievementsData.forEach(a=>{state.achievements[a.id]=false;});}
function saveState(){try{localStorage.setItem(stateKey(),JSON.stringify(state));}catch(e){showToast('Failed to save.','error');}}
function checkStreak(){const today=new Date().toDateString();const lastDate=state.user.streak.lastDate?new Date(state.user.streak.lastDate).toDateString():null;if(lastDate&&lastDate!==today){const yesterday=new Date();yesterday.setDate(yesterday.getDate()-1);if(lastDate!==yesterday.toDateString()){state.user.streak.count=0;}}}
function showLogin(){document.getElementById('loginModal').classList.add('active');document.getElementById('mainApp').style.display='none';document.getElementById('headerStats').style.display='none';document.getElementById('fab').style.display='none';document.getElementById('codeStep').style.display='block';document.getElementById('userStep').style.display='none';generateNewCode();}
function generateNewCode(){const code=Math.floor(100000+Math.random()*900000).toString();document.getElementById('displayCode').textContent=code;window.currentCode=code;}
function verifyCode(){const enteredCode=document.getElementById('verificationCode').value.trim();if(!enteredCode){showError('loginError','Enter verification code');return;}if(enteredCode!==window.currentCode){showError('loginError','Wrong code.');generateNewCode();return;}document.getElementById('codeStep').style.display='none';document.getElementById('userStep').style.display='block';document.getElementById('loginError').style.display='none';const allUsers=getAllUsers();const userSelect=document.getElementById('userSelect');userSelect.innerHTML='<option value="">-- Select --</option>';allUsers.forEach(user=>{const option=document.createElement('option');option.value=user.email;option.textContent=escapeHtml(user.name)+(user.role==='admin'?' 👑':'');userSelect.appendChild(option);});if(allUsers.length===0){document.getElementById('loginModal').classList.remove('active');openSetupModal();}}
function backToCode(){document.getElementById('codeStep').style.display='block';document.getElementById('userStep').style.display='none';document.getElementById('verificationCode').value='';document.getElementById('loginPassword').value='';}
async function handleLogin(){const email=document.getElementById('userSelect').value;const password=document.getElementById('loginPassword').value;if(!email||!password){showError('loginError','Select name and enter password');return;}const allUsers=getAllUsers();const user=allUsers.find(u=>u.email===email);if(!user){showError('loginError','User not found');return;}const passwordValid=await verifyPassword(password,user.passwordHash);if(!passwordValid){showError('loginError','Wrong password!');return;}currentUser=user;localStorage.setItem('focusforge-user',JSON.stringify({id:user.email,email:user.email,name:user.name,role:user.role}));showMainApp();}
function handleLogout(){if(confirm('Sign out?')){currentUser=null;localStorage.removeItem('focusforge-user');showLogin();}}
function showError(id,msg){const el=document.getElementById(id);if(el){el.textContent=msg;el.style.display='block';setTimeout(()=>el.style.display='none',5000);}}
function openSetupModal(){document.getElementById('setupModal').classList.add('active');document.getElementById('setupName').focus();}
function closeSetupModal(){document.getElementById('setupModal').classList.remove('active');if(getAllUsers().length===0)showLogin();}
async function handleSetup(){const name=document.getElementById('setupName').value.trim();const email=document.getElementById('setupEmail').value.trim();const password=document.getElementById('setupPassword').value;const confirm=document.getElementById('setupConfirm').value;if(!name||!email||!password){showToast('Fill all fields','error');return;}if(password.length<6){showToast('Password min 6 chars','error');return;}if(password!==confirm){showToast('Passwords differ','error');return;}const emailRegex=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;if(!emailRegex.test(email)){showToast('Invalid email','error');return;}const passwordHash=await hashPassword(password);const adminUser={name:name,email:email,passwordHash:passwordHash,role:'admin',createdAt:new Date().toISOString()};saveAllUsers([adminUser]);closeSetupModal();showToast('Admin created!','success');showLogin();}
function handleCodeKeydown(event){if(event.key==='Enter')verifyCode();}
function showMainApp(){const user=getCurrentUser();document.getElementById('userName').textContent=escapeHtml(user?.name||'Student');document.getElementById('loginModal').classList.remove('active');document.getElementById('mainApp').style.display='block';document.getElementById('headerStats').style.display='flex';document.getElementById('fab').style.display='flex';document.getElementById('adminBtn').style.display=user?.role==='admin'?'block':'none';loadState();renderSubjects();renderAchievements();updateUI();updateHeatmap();populateSubjectSelect();}
function updateUI(){document.getElementById('streakCount').textContent=state.user.streak.count;document.getElementById('headerStreak').textContent=state.user.streak.count;const multiplier=Math.min(1+(state.user.streak.count*0.1),2);document.getElementById('streakMultiplier').textContent=multiplier.toFixed(1)+'x';const currentLevel=levelsData.find(l=>l.level===state.user.level)||levelsData[0];const nextLevel=levelsData.find(l=>l.level===state.user.level+1);document.getElementById('headerLevel').textContent=currentLevel.name;document.getElementById('currentLevelName').textContent=currentLevel.name;document.getElementById('headerXP').textContent=state.user.xp+' XP';if(nextLevel){document.getElementById('nextLevelName').textContent=nextLevel.name+' ('+nextLevel.xpRequired+' XP)';const progress=((state.user.xp-currentLevel.xpRequired)/(nextLevel.xpRequired-currentLevel.xpRequired))*100;document.getElementById('levelFill').style.width=Math.min(progress,100)+'%';document.getElementById('xpProgress').textContent=Math.round(progress)+'%';document.getElementById('xpNeeded').textContent=state.user.xp+' / '+nextLevel.xpRequired+' XP';}else{document.getElementById('nextLevelName').textContent='MAX LEVEL!';document.getElementById('levelFill').style.width='100%';}document.getElementById('totalTime').textContent=Math.round(state.stats.totalStudyTime/60)+'h';document.getElementById('totalSessions').textContent=state.stats.sessionsCompleted;document.getElementById('longestStreak').textContent=state.stats.longestStreak;}
function renderSubjects(){const grid=document.getElementById('subjectsGrid');if(!grid)return;const subjects=Object.entries(state.subjects);if(subjects.length===0){grid.innerHTML='<p style="color:var(--text-muted);text-align:center;padding:40px;">No subjects. Click + Add!</p>';return;}grid.innerHTML=subjects.map(([id,subject])=>{const completed=subject.chapters.filter(c=>c.completed).length;const total=subject.chapters.length;const progress=total>0?(completed/total)*100:0;return'<div class="subject-card" style="--subject-color:'+escapeHtml(subject.color)+'" onclick="openChapterModal(\''+escapeHtml(id)+'\')" tabindex="0"><div class="subject-actions"><button class="action-btn delete" onclick="event.stopPropagation();deleteSubject(\''+escapeHtml(id)+'\')">🗑️</button></div><div class="subject-icon">'+subject.icon+'</div><div class="subject-name">'+escapeHtml(subject.name)+'</div><div class="subject-progress"><div class="subject-progress-fill" style="width:'+progress+'%"></div></div><div class="subject-stats"><span>'+completed+'/'+total+'</span><span>'+Math.round(progress)+'%</span></div></div>';}).join('');}
function renderAchievements(){const grid=document.getElementById('achievementsGrid');if(!grid)return;grid.innerHTML=achievementsData.map(a=>'<div class="achievement-card '+(state.achievements[a.id]?'unlocked':'locked')+'"><div class="achievement-icon">'+a.icon+'</div><div class="achievement-name">'+escapeHtml(a.name)+'</div></div>').join('');}
function updateHeatmap(){const grid=document.getElementById('heatmapGrid');if(!grid)return;const dateMap={};state.sessions.forEach(session=>{dateMap[new Date(session.date).toDateString()]=(dateMap[new Date(session.date).toDateString()]||0)+1;});let cells='';for(let i=27;i>=0;i--){const date=new Date();date.setDate(date.getDate()-i);const count=dateMap[date.toDateString()]||0;let level='';if(count>=4)level='level-4';else if(count>=3)level='level-3';else if(count>=2)level='level-2';else if(count>=1)level='level-1';cells+='<div class="heatmap-cell '+level+'" title="'+escapeHtml(date.toLocaleDateString()+': '+count+' sessions')+'"></div>';}grid.innerHTML=cells;}
function populateSubjectSelect(){['sessionSubject','testSubject'].forEach(selectId=>{const select=document.getElementById(selectId);if(!select)return;select.innerHTML='<option value="">Select Subject</option>';Object.entries(state.subjects).forEach(([id,subject])=>{const option=document.createElement('option');option.value=id;option.textContent=subject.icon+' '+subject.name;select.appendChild(option);});});}
function openSubjectModal(){document.getElementById('subjectName').value='';selectedColor='#6366f1';selectedIcon='📚';selectedPriority='high';document.querySelectorAll('#colorPicker .color-option').forEach(opt=>{opt.classList.toggle('selected',opt.dataset.color===selectedColor);});document.querySelectorAll('#iconPicker .icon-option').forEach(opt=>{opt.classList.toggle('selected',opt.dataset.icon===selectedIcon);});document.querySelectorAll('.priority-btn').forEach(btn=>{btn.classList.toggle('active',btn.dataset.priority===selectedPriority);});document.getElementById('subjectModal').classList.add('active');document.getElementById('subjectName').focus();}
function closeSubjectModal(){document.getElementById('subjectModal').classList.remove('active');}
function selectColor(el){selectedColor=el.dataset.color;document.querySelectorAll('#colorPicker .color-option').forEach(opt=>{opt.classList.remove('selected');});el.classList.add('selected');}
function selectIcon(el){selectedIcon=el.dataset.icon;document.querySelectorAll('#iconPicker .icon-option').forEach(opt=>{opt.classList.remove('selected');});el.classList.add('selected');}
function selectPriority(el){selectedPriority=el.dataset.priority;document.querySelectorAll('.priority-btn').forEach(btn=>{btn.classList.remove('active');});el.classList.add('active');}
function saveSubject(){const name=document.getElementById('subjectName').value.trim();if(!name){showToast('Enter name','error');return;}const id='subject-'+Date.now();state.subjects[id]={name:name,color:selectedColor,icon:selectedIcon,chapters:[],priority:selectedPriority};saveState();closeSubjectModal();renderSubjects();populateSubjectSelect();showToast('Subject created!','success');}
function deleteSubject(id){const subject=state.subjects[id];if(!subject)return;if(!confirm('Delete "'+subject.name+'"?'))return;delete state.subjects[id];saveState();renderSubjects();populateSubjectSelect();}
let currentSubjectForChapters=null;
function openChapterModal(subjectId){currentSubjectForChapters=subjectId;const subject=state.subjects[subjectId];if(!subject)return;document.getElementById('chapterSubjectName').textContent=subject.icon+' '+subject.name;renderChapters();document.getElementById('chapterModal').classList.add('active');}
function closeChapterModal(){document.getElementById('chapterModal').classList.remove('active');currentSubjectForChapters=null;}
function renderChapters(){const list=document.getElementById('chaptersList');const subject=state.subjects[currentSubjectForChapters];if(!subject||!list)return;if(subject.chapters.length===0){list.innerHTML='<p style="color:var(--text-muted);text-align:center;">No chapters yet.</p>';return;}list.innerHTML=subject.chapters.map((chapter,index)=>'<div class="chapter-item"><button class="chapter-checkbox '+(chapter.completed?'checked':'')+'" onclick="toggleChapter('+index+')"><svg viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></svg></button><div class="chapter-info"><div class="chapter-name '+(chapter.completed?'completed':'')+'">'+escapeHtml(chapter.name)+'</div><div class="chapter-meta"><span>'+chapter.xp+' XP</span><div class="chapter-rating">'+[1,2,3,4,5].map(star=>'<button class="star '+(star<=chapter.rating?'filled':'')+'" onclick="setChapterRating('+index+','+star+')">★</button>').join('')+'</div></div></div><div class="chapter-actions"><button class="action-btn delete" onclick="deleteChapter('+index+')">🗑️</button></div></div>').join('');}
function toggleChapter(index){const subject=state.subjects[currentSubjectForChapters];if(!subject||!subject.chapters[index])return;subject.chapters[index].completed=!subject.chapters[index].completed;if(subject.chapters[index].completed&&!subject.chapters[index].xp){subject.chapters[index].xp=50;addXP(50);}saveState();renderChapters();renderSubjects();checkAchievements();}
function setChapterRating(index,rating){const subject=state.subjects[currentSubjectForChapters];if(!subject||!subject.chapters[index])return;subject.chapters[index].rating=rating;saveState();renderChapters();}
function openAddChapterInput(){document.getElementById('addChapterInput').style.display='block';document.getElementById('newChapterName').value='';document.getElementById('newChapterName').focus();}
function closeAddChapterInput(){document.getElementById('addChapterInput').style.display='none';}
function saveNewChapter(){const name=document.getElementById('newChapterName').value.trim();if(!name){showToast('Enter name','error');return;}const subject=state.subjects[currentSubjectForChapters];if(!subject)return;subject.chapters.push({id:'chapter-'+Date.now(),name:name,priority:subject.priority,completed:false,rating:0,xp:0});saveState();closeAddChapterInput();renderChapters();renderSubjects();showToast('Chapter added!','success');}
function deleteChapter(index){const subject=state.subjects[currentSubjectForChapters];if(!subject||!subject.chapters[index])return;if(!confirm('Delete?'))return;subject.chapters.splice(index,1);saveState();renderChapters();renderSubjects();}
function selectDuration(el){selectedDuration=parseInt(el.dataset.duration);document.querySelectorAll('.duration-btn').forEach(btn=>{btn.classList.remove('active');});el.classList.add('active');timerSeconds=selectedDuration*60;updateTimerDisplay();}
function selectSessionType(el){sessionType=el.dataset.type;document.querySelectorAll('.type-btn').forEach(btn=>{btn.classList.remove('active');});el.classList.add('active');}
function startTimer(){if(timerRunning){timerRunning=false;timerPaused=true;clearInterval(timerInterval);document.getElementById('startBtn').innerHTML='Resume';document.getElementById('timerProgress').classList.add('paused');return;}if(timerPaused){timerRunning=true;timerPaused=false;}else{timerSeconds=selectedDuration*60;sessionStartTime=new Date();currentSubjectId=document.getElementById('sessionSubject').value;}timerRunning=true;document.getElementById('startBtn').style.display='none';document.getElementById('resetBtn').style.display='block';document.getElementById('timerProgress').classList.remove('paused');if(sessionType==='focus'){document.getElementById('timerProgress').classList.remove('break');document.getElementById('timerLabel').textContent='Focus Time';document.getElementById('focusOverlay').classList.add('active');const subject=currentSubjectId?state.subjects[currentSubjectId]:null;document.getElementById('focusSubject').textContent=subject?subject.name:'General';document.getElementById('focusTimer').textContent=formatTime(timerSeconds);}else{document.getElementById('timerProgress').classList.add('break');document.getElementById('timerLabel').textContent='Break Time';}timerInterval=setInterval(()=>{timerSeconds--;updateTimerDisplay();if(sessionType==='focus')document.getElementById('focusTimer').textContent=formatTime(timerSeconds);if(timerSeconds<=0)completeSession();},1000);}
function resetTimer(){timerRunning=false;timerPaused=false;clearInterval(timerInterval);timerSeconds=selectedDuration*60;document.getElementById('startBtn').style.display='block';document.getElementById('startBtn').innerHTML='Start Session';document.getElementById('resetBtn').style.display='none';document.getElementById('timerProgress').classList.remove('paused','break');document.getElementById('focusOverlay').classList.remove('active');document.getElementById('timerLabel').textContent='Focus Time';updateTimerDisplay();}
function stopTimer(){if(timerRunning&&sessionType==='focus'){const elapsed=Math.round((selectedDuration*60-timerSeconds)/60);if(elapsed>=5){addXP(Math.round(elapsed*2));showToast('Earned XP for '+elapsed+'min','warning');}}resetTimer();}
function completeSession(){clearInterval(timerInterval);timerRunning=false;if(sessionType==='focus'){const baseXP=selectedDuration*2;const streakMult=Math.min(1+(state.user.streak.count*0.1),2);const earnedXP=Math.round(baseXP*streakMult);addXP(earnedXP);state.sessions.push({date:new Date().toISOString(),duration:selectedDuration,subjectId:currentSubjectId,xp:earnedXP});state.stats.sessionsCompleted++;state.stats.totalStudyTime+=selectedDuration;state.user.streak.lastDate=new Date().toISOString();state.user.streak.count++;if(state.user.streak.count>state.stats.longestStreak)state.stats.longestStreak=state.user.streak.count;saveState();checkAchievements();showToast('Session complete! +'+earnedXP+' XP!','success');document.getElementById('focusLabel').textContent='Session Complete!';document.getElementById('focusSubject').textContent='+'+earnedXP+' XP';setTimeout(()=>{resetTimer();},2000);}else{showToast('Break complete!','success');resetTimer();}updateUI();updateHeatmap();}
function updateTimerDisplay(){const m=Math.floor(timerSeconds/60);const s=timerSeconds%60;document.getElementById('timerDisplay').textContent=m+':'+s.toString().padStart(2,'0');document.getElementById('timerProgress').style.strokeDashoffset=2*Math.PI*90*(1-((selectedDuration*60-timerSeconds)/(selectedDuration*60)));}
function formatTime(s){return Math.floor(s/60)+':'+(s%60).toString().padStart(2,'0');}
function addXP(amount){state.user.xp+=amount;const nextLevel=levelsData.find(l=>l.level===state.user.level+1);if(nextLevel&&state.user.xp>=nextLevel.xpRequired){state.user.level++;showToast('Level Up! '+nextLevel.name+'!','success');}saveState();updateUI();}
function checkAchievements(){if(!state.achievements['first-session']&&state.stats.sessionsCompleted>=1)state.achievements['first-session']=true;if(!state.achievements['streak-3']&&state.user.streak.count>=3)state.achievements['streak-3']=true;if(!state.achievements['streak-7']&&state.user.streak.count>=7)state.achievements['streak-7']=true;if(!state.achievements['sessions-10']&&state.stats.sessionsCompleted>=10)state.achievements['sessions-10']=true;if(!state.achievements['hours-10']&&state.stats.totalStudyTime>=600)state.achievements['hours-10']=true;renderAchievements();}
function handleChatKeydown(event){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();sendMessage();}}
function addChatMessage(content,type){const messages=document.getElementById('chatMessages');const el=document.createElement('div');el.className='chat-message '+type;el.innerHTML=content;messages.appendChild(el);messages.scrollTop=messages.scrollHeight;}
function getBotResponse(msg){const m=msg.toLowerCase();if(m.includes('quadratic'))return'📐 <b>Quadratic Equations</b><br><br>Key: ax²+bx+c=0<br>Formula: x=(-b±√(b²-4ac))/2a<br><br>ICSE Tips:<br>• Check discriminant<br>• Sum=-b/a, Product=c/a';if(m.includes('trigonometry')||m.includes('trig')||m.includes('sin')||m.includes('cos'))return'📐 <b>Trigonometry</b><br><br>Key: sin²θ+cos²θ=1<br>tanθ=sinθ/cosθ<br><br>sin30°=½,cos45°=√2/2';if(m.includes('electrostatics')||m.includes('electric'))return'🔬 <b>Electrostatics</b><br><br>Like charges repel<br>Coulomb\'s Law: F=kq₁q₂/r²<br>Charge: e=1.6×10⁻¹⁹C';if(m.includes('bonding')||m.includes('bond'))return'🧪 <b>Chemical Bonding</b><br><br>Ionic-electron transfer<br>Covalent-electron sharing<br>Remember octet rule!';if(m.includes('periodic'))return'🧪 <b>Periodic Table</b><br><br>Trends:<br>Atomic size decreases →<br>Group 1:Alkali,17:Halogens';if(m.includes('study')&&(m.includes('tip')||m.includes('help')))return'💡 <b>Study Tips</b><br><br>1.Focus on concepts<br>2.Practice past papers<br>3.Summary notes<br>4.Pomodoro technique<br>5.Diagrams matter!';return'🤔 Topics: Math,Physics,Chemistry,English<br>Try specific topics!';}
function selectMarks(el){testMarks=parseInt(el.dataset.marks);document.querySelectorAll('.test-option').forEach(opt=>{opt.classList.remove('selected');});el.classList.add('selected');}
function generateTestPaper(){const subjectId=document.getElementById('testSubject').value;const chapter=document.getElementById('testChapter').value.trim();const subject=subjectId?state.subjects[subjectId]:null;const subName=subject?subject.name:'General';const topic=chapter||'Various';let q='';if(testMarks===20)q='**Section A**[10]<br>1.Define '+topic+'<br>2.Characteristics<br>3.Formula<br><br>**Section B**[10-2]<br>4.Explain+diagram<br>5.Differentiate<br>6.Numerical';else if(testMarks===50)q='**Section A**[20]<br>1.Define[2]<br>2.Principle[2]<br>3.Applications[4]<br>4.Diagram[6]<br>5.Mechanism[6]<br><br>**Section B**[30-3]<br>6.Parts[10]<br>7-9.Numericals[5each]';else q='**Section A**[40]<br>1.Define&explain[8]<br>2.Diagram[8]<br>3.Laws[8]<br>4.Notes[12]<br>5.Derive[4]<br><br>**Section B**[60-4]<br>6-11.Numericals,Essays[15each]';document.getElementById('testPaperContent').innerHTML='<div class="test-paper-header"><div class="test-paper-title">ICSE TEST PAPER</div><div>Subject:'+escapeHtml(subName)+' | Topic:'+escapeHtml(topic)+'</div><div>Marks:'+testMarks+' | Time:'+testMarks+'min</div></div>'+q.replace(/\n/g,'<br>').replace(/\*\*/g,'');document.getElementById('testOutput').classList.add('active');showToast('Generated!','success');}
function copyTest(){const content=document.getElementById('testPaperContent').innerText;navigator.clipboard.writeText(content).then(()=>{showToast('Copied!','success');});}
function openAdminModal(){renderAdminUserList();updateAdminStats();updateAIStatus();const keyInput=document.getElementById('geminiApiKey');if(keyInput)keyInput.value=getGeminiKey();document.getElementById('adminModal').classList.add('active');}
function closeAdminModal(){document.getElementById('adminModal').classList.remove('active');}
function switchAdminTab(tab,el){document.querySelectorAll('.admin-tab').forEach(t=>{t.classList.remove('active');});if(el)el.classList.add('active');document.getElementById('adminUsersTab').style.display=tab==='users'?'block':'none';document.getElementById('adminStatsTab').style.display=tab==='stats'?'block':'none';document.getElementById('adminSettingsTab').style.display=tab==='settings'?'block':'none';}
function updateAdminStats(){const allUsers=getAllUsers();document.getElementById('adminTotalUsers').textContent=allUsers.length;document.getElementById('adminTotalXP').textContent=state.user.xp;document.getElementById('adminTotalSessions').textContent=state.stats.sessionsCompleted;document.getElementById('adminTotalTime').textContent=Math.round(state.stats.totalStudyTime/60)+'h';}
function renderAdminUserList(){const allUsers=getAllUsers();const container=document.getElementById('adminUserList');container.innerHTML=allUsers.map((user,index)=>'<div class="user-card"><div class="user-info"><div class="user-avatar">'+escapeHtml(user.name.charAt(0).toUpperCase())+'</div><div class="user-details"><h4>'+escapeHtml(user.name)+' <span class="user-role '+escapeHtml(user.role)+'">'+escapeHtml(user.role)+'</span></h4><p>'+escapeHtml(user.email)+'</p></div></div><div class="user-controls"><button class="btn btn-secondary btn-small" onclick="openEditUserModal('+index+')">✏️ Edit</button></div></div>').join('');}
function openAddUserModal(){document.getElementById('newUserName').value='';document.getElementById('newUserEmail').value='';document.getElementById('newUserPassword').value='';newUserRole='student';document.getElementById('roleStudent').className='btn btn-primary';document.getElementById('roleAdmin').className='btn btn-secondary';document.getElementById('addUserModal').classList.add('active');}
function closeAddUserModal(){document.getElementById('addUserModal').classList.remove('active');}
function setNewUserRole(role){newUserRole=role;document.getElementById('roleStudent').className=role==='student'?'btn btn-primary':'btn btn-secondary';document.getElementById('roleAdmin').className=role==='admin'?'btn btn-primary':'btn btn-secondary';}
async function saveNewUser(){const name=document.getElementById('newUserName').value.trim();const email=document.getElementById('newUserEmail').value.trim();const password=document.getElementById('newUserPassword').value;if(!name||!email||!password){showToast('Fill all fields','error');return;}if(password.length<4){showToast('Password min 4','error');return;}const allUsers=getAllUsers();if(allUsers.find(u=>u.email===email)){showToast('Email exists!','error');return;}const passwordHash=await hashPassword(password);allUsers.push({name:name,email:email,passwordHash:passwordHash,role:newUserRole,createdAt:new Date().toISOString()});saveAllUsers(allUsers);closeAddUserModal();renderAdminUserList();updateAdminStats();showToast('User created!','success');}
function openEditUserModal(index){const allUsers=getAllUsers();const user=allUsers[index];document.getElementById('editUserIndex').value=index;document.getElementById('editUserName').value=user.name;document.getElementById('editUserEmail').value=user.email;document.getElementById('editUserPassword').value='';editUserRole=user.role;document.getElementById('editRoleStudent').className=user.role==='student'?'btn btn-primary':'btn btn-secondary';document.getElementById('editRoleAdmin').className=user.role==='admin'?'btn btn-primary':'btn btn-secondary';document.getElementById('editUserModal').classList.add('active');}
function closeEditUserModal(){document.getElementById('editUserModal').classList.remove('active');}
function setEditUserRole(role){editUserRole=role;document.getElementById('editRoleStudent').className=role==='student'?'btn btn-primary':'btn btn-secondary';document.getElementById('editRoleAdmin').className=role==='admin'?'btn btn-primary':'btn btn-secondary';}
async function updateUser(){const index=parseInt(document.getElementById('editUserIndex').value);const name=document.getElementById('editUserName').value.trim();const newPassword=document.getElementById('editUserPassword').value;if(!name){showToast('Enter name','error');return;}const allUsers=getAllUsers();allUsers[index].name=name;allUsers[index].role=editUserRole;if(newPassword&&newPassword.length>=4)allUsers[index].passwordHash=await hashPassword(newPassword);saveAllUsers(allUsers);closeEditUserModal();renderAdminUserList();if(currentUser&&currentUser.email===allUsers[index].email){currentUser=allUsers[index];localStorage.setItem('focusforge-user',JSON.stringify({id:currentUser.email,email:currentUser.email,name:currentUser.name,role:currentUser.role}));document.getElementById('userName').textContent=currentUser.name;}showToast('Updated!','success');}
function deleteUser(){const index=parseInt(document.getElementById('editUserIndex').value);const allUsers=getAllUsers();const user=allUsers[index];if(user.role==='admin'){showToast('Cannot delete admin!','error');return;}if(!confirm('Delete "'+user.name+'"?'))return;allUsers.splice(index,1);saveAllUsers(allUsers);closeEditUserModal();renderAdminUserList();updateAdminStats();showToast('Deleted!','success');}
function exportUsersCSV(){const allUsers=getAllUsers();let csv='Name,Email,Role\n';allUsers.forEach(u=>{csv+=escapeHtml(u.name)+','+escapeHtml(u.email)+','+escapeHtml(u.role)+'\n';});const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='focusforge-users.csv';a.click();URL.revokeObjectURL(url);showToast('CSV exported!','success');}
function exportUserData(){const data={exportDate:new Date().toISOString(),users:getAllUsers().map(u=>({name:u.name,email:u.email,role:u.role})),stats:state.stats};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='focusforge-export.json';a.click();URL.revokeObjectURL(url);}
function downloadBackup(){const backup={backupDate:new Date().toISOString(),state:state,user:getCurrentUser()};const blob=new Blob([JSON.stringify(backup,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='focusforge-backup.json';a.click();URL.revokeObjectURL(url);showToast('Backup downloaded!','success');}
function handleRestore(event){const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=(e)=>{try{const data=JSON.parse(e.target.result);if(data.state){state=data.state;saveState();loadState();updateUI();renderSubjects();renderAchievements();updateHeatmap();showToast('Restored!','success');}else showToast('Invalid','error');}catch(err){showToast('Parse failed','error');}};reader.readAsText(file);event.target.value='';}
function resetAllData(){if(!confirm('Delete ALL data?'))return;if(!confirm('Final warning!'))return;const keys=[];for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key&&key.startsWith('focusforge-'))keys.push(key);}keys.forEach(key=>localStorage.removeItem(key));closeAdminModal();currentUser=null;showLogin();showToast('Reset.','warning');}
function showToast(message,type='info'){const container=document.getElementById('toastContainer');const toast=document.createElement('div');toast.className='toast '+type;toast.textContent=message;toast.setAttribute('role','alert');container.appendChild(toast);setTimeout(()=>{toast.style.opacity='0';setTimeout(()=>toast.remove(),300);},4000);}

/* ===== PASSWORD TOGGLE ===== */
function togglePassword(inputId,btn){const input=document.getElementById(inputId);if(!input)return;const isPassword=input.type==='password';input.type=isPassword?'text':'password';btn.classList.toggle('active',isPassword);btn.setAttribute('aria-label',isPassword?'Hide password':'Show password');}

/* ===== AI CHATBOT (Puter.js + Gemini fallback) ===== */
const AI_SYSTEM_PROMPT = 'You are FocusForge AI, a friendly and knowledgeable study assistant for ICSE Class 10 students. Help with Math, Physics, Chemistry, Biology, and English. Give clear, concise explanations suitable for a 15-16 year old. Use simple formatting with line breaks. If asked about non-study topics, gently redirect to studying. Keep responses under 250 words unless asked for more detail.';

function getGeminiKey(){const user=getCurrentUser();const key=user?'focusforge-gemini-key-'+user.email:'focusforge-gemini-key';return localStorage.getItem(key)||'';}

function saveGeminiKey(){const key=document.getElementById('geminiApiKey').value.trim();if(!key){showToast('Enter an API key','error');return;}const user=getCurrentUser();const storageKey=user?'focusforge-gemini-key-'+user.email:'focusforge-gemini-key';localStorage.setItem(storageKey,key);updateAIStatus();showToast('Gemini key saved!','success');}

function clearGeminiKey(){const user=getCurrentUser();const storageKey=user?'focusforge-gemini-key-'+user.email:'focusforge-gemini-key';localStorage.removeItem(storageKey);document.getElementById('geminiApiKey').value='';updateAIStatus();showToast('Gemini key cleared','warning');}

function updateAIStatus(){const el=document.getElementById('aiStatus');if(!el)return;const key=getGeminiKey();if(key){el.innerHTML='<span class="ai-badge online">🟢 Gemini override active</span>';}else{el.innerHTML='<span class="ai-badge online">🟢 Using Puter AI (default)</span>';}}

async function sendMessage(){const input=document.getElementById('chatInput');const msg=input.value.trim();if(!msg)return;addChatMessage(escapeHtml(msg),'user');input.value='';addTypingIndicator();try{const response=await callAI(msg);removeTypingIndicator();addChatMessage(response,'bot');}catch(err){removeTypingIndicator();console.error('AI error:',err);addChatMessage(getBotResponse(msg),'bot');}}

async function callAI(userMessage){const geminiKey=getGeminiKey();if(geminiKey){try{return await callGeminiAPI(userMessage);}catch(e){console.warn('Gemini failed, falling back to Puter:',e);}}if(typeof puter!=='undefined'&&puter.ai){return await callPuterAI(userMessage);}throw new Error('No AI available');}

async function callPuterAI(userMessage){const response=await puter.ai.chat([{role:'system',content:AI_SYSTEM_PROMPT},{role:'user',content:userMessage}],{model:'google/gemini-2.0-flash',stream:true});let text='';for await(const part of response){if(part?.text){text+=part.text;}}if(!text)throw new Error('Empty Puter response');const formatted=escapeHtml(text).replace(/\n/g,'<br>');return formatted;}

async function callGeminiAPI(userMessage){const key=getGeminiKey();const url='https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key='+key;const body={contents:[{parts:[{text:AI_SYSTEM_PROMPT+'\n\nStudent asks: '+userMessage}]}],generationConfig:{temperature:0.7,maxOutputTokens:500}};const res=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!res.ok){const errData=await res.json().catch(()=>({}));throw new Error(errData.error?.message||'API error ('+res.status+')');}const data=await res.json();const text=data.candidates?.[0]?.content?.parts?.[0]?.text;if(!text)throw new Error('No response');return escapeHtml(text).replace(/\n/g,'<br>');}

function addTypingIndicator(){const messages=document.getElementById('chatMessages');const el=document.createElement('div');el.className='typing-indicator';el.id='typingIndicator';el.innerHTML='<div class="typing-dot"></div><div class="typing-dot"></div><div class="typing-dot"></div>';messages.appendChild(el);messages.scrollTop=messages.scrollHeight;}

function removeTypingIndicator(){const el=document.getElementById('typingIndicator');if(el)el.remove();}

function sendQuickMessage(topic){document.getElementById('chatInput').value=topic;sendMessage();}

/* ===== INIT ===== */
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',init);}else{init();}
